<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    public function index()
    {
        return response()->json([
            'service_name' => 'PHP Service App',
            'status' => 'Running',
            'endpoints' => [
                'latihan1' => [
                    'GET /latihan1/hello-lumen',
                    'GET /latihan1/hello-lumen/{name}',
                    'GET /latihan1/scores (with login middleware)',
                    'GET /latihan1/users',
                    'GET /latihan1/users/{id}',
                    'GET /latihan1/books',
                    'GET /latihan1/cities',
                    'GET /latihan1/profile/{id}',
                    'GET /latihan1/status',
                    'GET /latihan1/secure-data (with apikey middleware)',
                ],
                'latihan2' => [
                    'GET /latihan2/posts',
                    'GET /latihan2/articles',
                    'GET /latihan2/articles/{id}',
                    'POST /latihan2/articles',
                    'GET /latihan2/authors',
                    'GET /latihan2/categories',
                    'GET /latihan2/comments',
                    'GET /latihan2/tags',
                ],
                'latihan3' => [
                    'GET /latihan3/posts',
                    'POST /latihan3/posts',
                    'GET /latihan3/post/{id}',
                    'PUT /latihan3/post/{id}',
                    'DELETE /latihan3/post/{id}',
                    'GET /latihan3/products',
                    'POST /latihan3/products',
                    'GET /latihan3/product/{id}',
                    'PUT /latihan3/product/{id}',
                    'DELETE /latihan3/product/{id}',
                ],
                'uts' => [
                    'GET /uts/customers',
                    'POST /uts/customers',
                    'GET /uts/customer/{id}',
                    'PUT /uts/customer/{id}',
                    'DELETE /uts/customer/{id}',
                    'GET /uts/orders',
                    'POST /uts/orders',
                    'GET /uts/order/{id}',
                    'PUT /uts/order/{id}',
                    'DELETE /uts/order/{id}',
                    'GET /uts/employees',
                    'POST /uts/employees',
                    'GET /uts/employee/{id}',
                    'PUT /uts/employee/{id}',
                    'DELETE /uts/employee/{id}',
                ],
                'latihan4' => [
                    'GET /latihan4/posts',
                    'POST /latihan4/posts',
                    'GET /latihan4/post/{id}',
                    'PUT /latihan4/post/{id}',
                    'DELETE /latihan4/post/{id}',
                ],
                'latihan5' => [
                    'GET /latihan5/posts',
                    'POST /latihan5/posts',
                    'GET /latihan5/post/{id}',
                    'PUT /latihan5/post/{id}',
                    'DELETE /latihan5/post/{id}',
                ],
                'latihan6' => [
                    'GET /latihan6/posts (with auth middleware)',
                    'POST /latihan6/posts (with auth middleware)',
                    'GET /latihan6/post/{id} (with auth middleware)',
                    'PUT /latihan6/post/{id} (with auth middleware)',
                    'DELETE /latihan6/post/{id} (with auth middleware)',
                    'GET /latihan6/books (with auth middleware)',
                    'POST /latihan6/books (with auth middleware)',
                    'GET /latihan6/book/{id} (with auth middleware)',
                    'PUT /latihan6/book/{id} (with auth middleware)',
                    'DELETE /latihan6/book/{id} (with auth middleware)',
                ],
                'uas' => [
                    'GET /uas/projects',
                    'POST /uas/projects',
                    'GET /uas/project/{id}',
                    'PUT /uas/project/{id}',
                    'DELETE /uas/project/{id}',
                    'GET /uas/tasks',
                    'POST /uas/tasks',
                    'GET /uas/task/{id}',
                    'PUT /uas/task/{id}',
                    'DELETE /uas/task/{id}',
                    'GET /uas/events',
                    'POST /uas/events',
                    'GET /uas/event/{id}',
                    'PUT /uas/event/{id}',
                    'DELETE /uas/event/{id}',
                    'GET /uas/notes',
                    'POST /uas/notes',
                    'GET /uas/note/{id}',
                    'PUT /uas/note/{id}',
                    'DELETE /uas/note/{id}',
                    'GET /uas/messages',
                    'POST /uas/messages',
                    'GET /uas/message/{id}',
                    'PUT /uas/message/{id}',
                    'DELETE /uas/message/{id}',
                ],
                'auth' => [
                    'POST /auth/register',
                    'POST /auth/login',
                ],
                'coba' => [
                    'GET /coba',
                ],
            ],
        ]);
    }
}
